[package]
name = "zero2prod"
version = "0.1.0"
authors = ["xiaomeng79 <496096100@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
